In [1]:
# Imports

from pathlib import Path
from scipy.io import savemat
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import re

In [2]:
# Define participant and set paths

participant = "vp04"

try:
    BASE_DIR = Path(__file__).resolve().parent
except NameError: 
    BASE_DIR = Path.cwd().parent
    
INPUT_PATH = BASE_DIR / "analysis" / "participants" / participant / "logs"
OUTPUT_PATH = BASE_DIR / "analysis" / "participants" / participant

os.chdir(INPUT_PATH)

print(BASE_DIR)
print(INPUT_PATH)
print(OUTPUT_PATH)

D:\thesis-matlab-pipeline
D:\thesis-matlab-pipeline\analysis\participants\vp04\logs
D:\thesis-matlab-pipeline\analysis\participants\vp04


In [3]:
# Get logs in dir

logs = [log for log in os.listdir() if log.endswith(".csv")]

print(logs)

['NH1.csv', 'NH2.csv']


In [4]:
def build_arrays(run_type):
    match run_type:
        case "func":
            condition_order = ["coherent", "incoherent_real", "incoherent_mock", "neutral", "target"]
        case "loc":
            condition_order = ["Face", "scene", "scrambled"]

    columns = len(condition_order)

    onset_array = np.empty((columns,), dtype=np.object_)
    duration_array = np.empty((columns,), dtype=np.object_)
    names_array = np.empty((columns,), dtype=np.object_)

    return condition_order, onset_array, duration_array, names_array

In [5]:
def write_conditions_and_onsets(log, condition_order, onset_array):
    for i, condition in enumerate(condition_order):
        cond_onst = list(log[log['condition'] == condition]['s2_onset_cor'])
        cond_onset_array = np.array([[num] for num in cond_onst])
        cond_onst = [float(str(num).replace(',', '.')) for num in cond_onst]
    
        cond_onset_array = np.array([[num] for num in cond_onst], dtype=float)
        cond_onset_array = cond_onset_array + 4
        onset_array[i] = cond_onset_array

    return onset_array

In [6]:
def write_durations(duration_array):
    duration_list = [0.20, 0.20, 0.20, 0.20, 0.20]

    for i, duration in enumerate(duration_list):
        duration_array[i] = duration

    return duration_array

In [7]:
def write_names(condition_order, names_array):
    for i, name in enumerate(condition_order):
        names_array[i] = name

    return names_array

In [8]:
def to_dict(onset_array, durration_array, names_array):
    mat_dict = {
        "onsets": onset_array,
        "names": names_array,
        "durations": duration_array,
    }

    return mat_dict

In [9]:
def prep_dir(log_id: str):
    match = re.search(r"\d+", log_id)
    log_number = match.group()

    func_dir = OUTPUT_PATH / f"0{log_number}_func"
    func_dir.mkdir(parents=True, exist_ok=True)

    return func_dir

In [10]:
def save_mcf(output_dir: Path, mat_dict: dict):
    out_dir = output_dir / "mcf"
    out_dir.mkdir(parents=True, exist_ok=True)

    out_file = out_dir / "MCF.mat"
    savemat(out_file, mat_dict)

In [11]:
# Run conversion for all files

for log in logs:
    log_path = INPUT_PATH / log
    df = pd.read_csv(log_path)

    if re.match(r".*localizer.*\.csv", log):
        run_type = "log"
    else: 
        run_type = "func"

    condition_order, empty_onset_array, empty_duration_array, empty_name_array = build_arrays(run_type)
    
    onset_array = write_conditions_and_onsets(df, condition_order, empty_onset_array)
    duration_array = write_durations(empty_duration_array)
    names_array = write_names(condition_order, empty_name_array)
    
    mat_dict = to_dict(onset_array, duration_array, names_array)
    
    mcf_dir = prep_dir(log)
    save_mcf(mcf_dir, mat_dict)
    
    print(f"MCF for {log} saved to {mcf_dir}.")
    for array, values in mat_dict.items():
        print(f"\narray")
        print("================")
        for value in values[0:5]:
            print(value)

print(f"MCF conversion completed for {logs}.")

MCF for NH1.csv saved to D:\thesis-matlab-pipeline\analysis\participants\vp04\01_func.
onsets
[[ 52.5227975]
 [ 86.5096792]
 [145.7869216]
 [155.0332562]
 [165.246072 ]
 [207.080075 ]
 [235.3358525]
 [243.5325785]
 [269.0055095]
 [289.7471481]
 [309.0059894]
 [318.5355312]
 [354.470916 ]
 [378.8610749]
 [422.4766461]
 [463.7435857]
 [515.4894864]]
[[ 33.7633627]
 [ 43.2929121]
 [ 68.6331075]
 [138.3895858]
 [182.5561276]
 [345.4912086]
 [362.5343947]
 [440.6027745]
 [533.5989323]
 [543.6116083]]
[[ 94.8063106]
 [103.2530977]
 [129.5928571]
 [192.0191692]
 [199.7827894]
 [216.8097266]
 [386.0414816]
 [412.2475873]
 [431.8230844]
 [448.4997304]
 [497.5134965]
 [524.7691388]]
[[ 24.3002811]
 [ 60.2530076]
 [173.2762387]
 [226.0395096]
 [252.4955675]
 [299.5598133]
 [336.0281804]
 [371.080869 ]
 [395.7543077]
 [403.800979 ]
 [455.7800926]
 [471.7569765]
 [479.3873066]]
[[ 14.1043796]
 [ 77.3463909]
 [113.5491633]
 [121.5627541]
 [261.1088103]
 [326.5155585]
 [489.6165136]
 [505.5100802]]
n